name: Aprendiendo Expresiones
run-name: ¡Estoy aprendiendo a usar las diferentes Expresiones!
on: 
  push:
    branches: ['master']
  pull_request:
    types: [opened, synchronize]
    branches: ['master','aprendiendo-**']
    paths: ['**.py']
  issues:
    types:
    - labeled
  workflow_dispatch:
    inputs:
      lenguaje_utilizado:
        description: 'Lenguaje utilizado'
        default: Python
        required: true
        type: choice
        options:
        - Python
        - JavaScript  
jobs:
  Python:
    if: ${{ inputs.lenguaje_utilizado == 'Python'}} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: echo El lenguaje seleccionado por el "USERNAME" es ${{ inputs.lenguaje_utilizado }} 
    
  Javascript:  
    if: ${{ inputs.lenguaje_utilizado == 'Javascrpt'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: echo El lenguaje seleccionado por el "USERNAME" es ${{ inputs.lenguaje_utilizado }} 
