name: Aprendiendo Triggers
run-name: ¡Estoy aprendiendo a usar los diferentes Triggers!
on: 
  push:
    branches: ['master']
  pull_request:
    types: [opened, synchronize]
    branches: ['master','aprendiendo-**']
    paths: ['**.py']
  issues:
    types:
    - labeled
  workflow_dispatch:
    inputs:
      lenguaje_utilizado:
        description: 'Lenguaje utilizado'
        default: Python
        required: true
        type: choice
        options:
        - Python
        - JavaScript  
  schedule:
    - cron: '30 9 * * *' #Horario UTS
  
jobs:
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch '}} #Se activa si el evento no es workflow_dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola_mundo.py
